# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script# Packages for latest PHP
sudo add-apt-repository ppa:ondrej/php5
sudo apt-get update
sudo tasksel install lamp-server
sudo apt-get install php5-gd php5-curl php5-cgi php5-dev php5-mcrypt php5-pspell php-apc php5-imagick phpmyadmin
wget -y
sudo a2enmod rewrite ssl actions
sudo a2dismod php5
sudo service apache2 restart

# MariaDB
http://stackoverflow.com/questions/16214517/installing-mariadb-unmet-dependencies-mariadb-server-5-5

# NGINX
http://www.organic-development.com/blog/apache-vs-nginx-performance-comparison.html
http://systemsarchitect.net/apache2-vs-nginx-for-php-application
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
